app/routes/blog_routes.py
# routes/blog_routes.py
from flask import Blueprint, render_template, redirect, url_for, session, request, flash
from datetime import datetime
from app import db
from app.model.model import BlogPost, Event, NewsArticle,User

blog_bp = Blueprint('blog', __name__)


@blog_bp.route('/bloog')
def bloog():
    blog_posts = BlogPost.query.all()
    events = Event.query.all()
    news_articles = NewsArticle.query.all()
    return render_template('c.html', blog_posts=blog_posts, events=events, news_articles=news_articles)


@blog_bp.route('/bagin', methods=['GET', 'POST'])
def bagin():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        if not username or not password:
            flash('Please enter both username and password.', 'error')
        else:
            find_user = User.query.filter_by(username=username).first()
            if find_user and find_user.password == password:
                session['admin_logged_in'] = True
                session['username'] = username
                session['role'] = find_user.role
                return redirect(url_for('blog.badmin'))
            else:
                flash('Invalid username or password.', 'error')
    return render_template('bagin.html')


@blog_bp.route('/bagout')
def bagout():
    session.pop('admin_logged_in', None)
    return redirect(url_for('home'))


@blog_bp.route('/badmin')
def badmin():
    posts = BlogPost.query.all()
    articles = NewsArticle.query.all()
    events = Event.query.all()
    return render_template('badmin.html', posts=posts, articles=articles, events=events)


@blog_bp.route('/badmin/blog/create', methods=['GET', 'POST'])
def create_blog_post():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        author = request.form['author']
        new_post = BlogPost(title=title, content=content, author=author)
        db.session.add(new_post)
        db.session.commit()
        flash('Blog post created successfully', 'success')
        return redirect(url_for('blog.badmin'))
    return render_template('create_blog_post.html')


@blog_bp.route('/badmin/blog/edit/<int:id>', methods=['GET', 'POST'])
def edit_blog_post(id):
    post = BlogPost.query.get(id)
    if request.method == 'POST':
        post.title = request.form['title']
        post.content = request.form['content']
        post.author = request.form['author']
        db.session.commit()
        flash('Blog post updated successfully', 'success')
        return redirect(url_for('blog.badmin'))
    return render_template('edit_blog_post.html', post=post)


@blog_bp.route('/badmin/blog/delete/<int:id>', methods=['POST'])
def delete_blog_post(id):
    post = BlogPost.query.get(id)
    db.session.delete(post)
    db.session.commit()
    flash('Blog post deleted successfully', 'success')
    return redirect(url_for('blog.badmin'))


@blog_bp.route('/badmin/events/create', methods=['GET', 'POST'])
def create_event():
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        date = datetime.strptime(request.form['date'], '%Y-%m-%d')
        location = request.form['location']
        new_event = Event(title=title, description=description,
                          date=date, location=location)
        db.session.add(new_event)
        db.session.commit()
        flash('Event created successfully', 'success')
        return redirect(url_for('blog.badmin'))
    return render_template('create_event.html')


@blog_bp.route('/badmin/events/edit/<int:id>', methods=['GET', 'POST'])
def edit_event(id):
    event = Event.query.get(id)
    if request.method == 'POST':
        event.title = request.form['title']
        event.description = request.form['description']
        event.date = datetime.strptime(request.form['date'], '%Y-%m-%d')
        event.location = request.form['location']
        db.session.commit()
        flash('Event updated successfully', 'success')
        return redirect(url_for('blog.badmin'))
    return render_template('edit_event.html', event=event)


@blog_bp.route('/badmin/events/delete/<int:id>', methods=['POST'])
def delete_event(id):
    event = Event.query.get(id)
    db.session.delete(event)
    db.session.commit()
    flash('Event deleted successfully', 'success')
    return redirect(url_for('blog.badmin'))


@blog_bp.route('/badmin/news/create', methods=['GET', 'POST'])
def create_news_article():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        author = request.form['author']
        new_article = NewsArticle(title=title, content=content, author=author)
        db.session.add(new_article)
        db.session.commit()
        flash('News article created successfully', 'success')
        return redirect(url_for('blog.badmin'))
    return render_template('create_news_article.html')


@blog_bp.route('/badmin/news/edit/<int:id>', methods=['GET', 'POST'])
def edit_news_article(id):
    article = NewsArticle.query.get(id)
    if request.method == 'POST':
        article.title = request.form['title']
        article.content = request.form['content']
        article.author = request.form['author']
        db.session.commit()
        flash('News article updated successfully', 'success')
        return redirect(url_for('blog.badmin'))
    return render_template('edit_news_article.html', article=article)


@blog_bp.route('/badmin/news/delete/<int:id>', methods=['POST'])
def delete_news_article(id):
    article = NewsArticle.query.get(id)
    db.session.delete(article)
    db.session.commit()
    flash('News article deleted successfully', 'success')
    return redirect(url_for('blog.badmin'))

app/routes/product_routes.py
from flask import Blueprint, render_template, redirect, url_for, session, request, flash
from werkzeug.utils import secure_filename
from app import db
from app.model.model import Product
from app.utils import allowed_file
import os
from dotenv import load_dotenv

product_bp = Blueprint('product', __name__)
load_dotenv()


@product_bp.route('/product/<int:product_id>')
def product_detail(product_id):
    product = Product.query.get_or_404(product_id)
    related_products = Product.query.filter(
        Product.id != product.id,
        Product.name.like(f'%{product.name.split()[0]}%')
    ).limit(4).all()
    return render_template('product_detail.html', product=product, related_products=related_products)


@product_bp.route('/prod')
def p_page():
    products = Product.query.all()
    return render_template('prod.html', products=products)


@product_bp.route('/admin/add_product', methods=['GET', 'POST'])
def add_product():
    if 'admin_logged_in' not in session or not session['admin_logged_in']:
        return redirect(url_for('admin.login'))
    if request.method == 'POST':
        name = request.form['name']
        price = request.form['price']
        description = request.form['description']
        image_file = request.files.get('image')
        if image_file and allowed_file(image_file.filename):
            filename = secure_filename(image_file.filename)
            image_path = os.path.join(os.getenv('UPLOAD_FOLDER'), filename)
            image_file.save(image_path)
            new_product = Product(name=name, price=price,
                                  image=filename, description=description)
            db.session.add(new_product)
            db.session.commit()
            new_product.log_action('Added', f'''Product'{name}'added successfully.''')

            flash('Product added successfully.', 'success')
            return redirect(url_for('admin.admin'))
        else:
            flash('No image selected or invalid file type.', 'error')
            return redirect(request.url)
    return render_template('add_product.html')


@product_bp.route('/admin/edit_product/<int:product_id>', methods=['GET', 'POST'])
def edit_product(product_id):
    if 'admin_logged_in' not in session or not session['admin_logged_in']:
        return redirect(url_for('admin.login'))
    product = Product.query.get_or_404(product_id)
    if request.method == 'POST':
        product.name = request.form['name']
        product.price = request.form['price']
        product.description = request.form['description']
        image_file = request.files.get('image')
        if image_file and allowed_file(image_file.filename):
            filename = secure_filename(image_file.filename)
            image_path = os.path.join(os.getenv('UPLOAD_FOLDER'), filename)
            image_file.save(image_path)
            product.image = filename
        db.session.commit()
        product.log_action('Edited',f"Product '{product.name}' edited successfully.")
        flash('Product updated successfully.', 'success')
        return redirect(url_for('admin.admin'))
    return render_template('edit_product.html', product=product)


@product_bp.route('/admin/delete_product/<int:product_id>', methods=['POST'])
def delete_product(product_id):
    if 'admin_logged_in' not in session or not session['admin_logged_in']:
        return redirect(url_for('admin.login'))
    product = Product.query.get_or_404(product_id)
    db.session.delete(product)
    db.session.commit()
    product.log_action('Deleted',f"Product '{product.name}' deleted successfully")
    flash('Product deleted successfully.', 'success')
    return redirect(url_for('admin.admin'))

app/routes/vacancy_routes.py
# routes/vacancy_routes.py
from flask import Blueprint, render_template, redirect, url_for, session, request, flash
from datetime import datetime
from app import db
from app.model.model import Job, AppliedJob,User
import os

from dotenv import load_dotenv


vacancy_bp = Blueprint('vacancy', __name__)
load_dotenv()


@vacancy_bp.route('/vadmin/add_job', methods=['GET', 'POST'])
def add_job():
    if 'admin_logged_in' not in session or not session['admin_logged_in']:
        return redirect(url_for('login'))

    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        requirements = request.form['requirements']
        deadline = datetime.strptime(
            request.form['deadline'], '%Y-%m-%dT%H:%M')
        job = Job(title=title, description=description,
                  requirements=requirements, deadline=deadline)
        db.session.add(job)
        db.session.commit()
        job.log_action('Added', f"Job '{title}' added successfully.")
        return "Job added successfully!"
    return render_template('add_job.html')


@vacancy_bp.route('/vadmin/delete_job/<int:job_id>', methods=['POST'])
def delete_job(job_id):
    job = Job.query.get(job_id)
    db.session.delete(job)
    db.session.commit()
    job.log_action('Deleted', f"Job '{job.title}' deleted successfully.")
    return redirect(url_for('vacancy.vadmin'))


@vacancy_bp.route('/vacancy')
def vacancy():
    jobs = Job.query.filter_by(is_active=True).all()
    return render_template('vacancy.html', jobs=jobs)


@vacancy_bp.route('/search', methods=['GET', 'POST'])
def search():
    if request.method == 'POST':
        search_term = request.form['search_term']
        jobs = Job.query.filter(Job.title.ilike(f'%{search_term}%')).all()
        return render_template('search_results.html', jobs=jobs, search_term=search_term)
    return redirect(url_for('home'))


@vacancy_bp.route('/lagin', methods=['GET', 'POST'])
def lagin():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        if not username or not password:
            flash('Please enter both username and password.', 'error')
        else:
            find_user = User.query.filter_by(username=username).first()
            if find_user and find_user.password == password:
                session['admin_logged_in'] = True
                session['username'] = username
                session['role'] = find_user.role
                return redirect(url_for('vacancy.vadmin'))
            else:
                return render_template('lagin.html', error='Invalid username or password')
    return render_template('lagin.html')


@vacancy_bp.route('/lagout')
def lagout():
    session.pop('admin_logged_in', None)
    return redirect(url_for('vacancy.lagin'))


@vacancy_bp.route('/lagin/vadmin')
def vadmin():
    jobs = Job.query.all()
    return render_template('vadmin.html', jobs=jobs)


@vacancy_bp.route('/vadmin/applied_jobs/<int:job_id>')
def applied_jobs(job_id):
    applied_jobs = AppliedJob.query.filter_by(job_id=job_id).all()
    return render_template('applied_jobs.html', applied_jobs=applied_jobs, job_id=job_id)


@vacancy_bp.route('/vadmin/delete_applied_job/<int:applied_job_id>', methods=['POST'])
def delete_applied_job(applied_job_id):
    applied_job = AppliedJob.query.get(applied_job_id)
    db.session.delete(applied_job)
    db.session.commit()
    applied_job.log_action('Deleted', f"Applied job with ID '{applied_job_id}' deleted successfully.")
    return redirect(url_for('vacancy.applied_jobs', job_id=applied_job.job_id))


@vacancy_bp.route('/apply/<int:job_id>', methods=['GET', 'POST'])
def apply(job_id):
    job = Job.query.get(job_id)
    current_time = datetime.now()
    if job.deadline and job.deadline < current_time:
        return render_template('apply.html', job=job, error='Application deadline has passed.', current_time=current_time)
    if request.method == 'POST':
        first_name = request.form['first_name']
        father_name = request.form['father_name']
        email = request.form['email']
        gender = request.form['gender']
        age = request.form['age']
        cv = request.files['cv']
        cv.save(os.path.join(os.getenv('UPLOAD_FOLDER'), cv.filename))
        applied_job = AppliedJob(
            job_id=job_id,
            first_name=first_name,
            father_name=father_name,
            applicant_email=email,
            gender=gender,
            age=age,
            cv_path=f"uploads/{cv.filename}"
        )
        db.session.add(applied_job)
        db.session.commit()
        return redirect(url_for('vacancy.vacancy'))
    return render_template('apply.html', job=job, current_time=current_time)

app/templates/add_product.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Discover AMCO Interior Design for top-quality furniture and exceptional interior design services in Addis Ababa, Ethiopia. Visit our store for the best furniture prices and designs. Find furniture in Ethiopia, a furniture store in Addis Ababa, and interior design services.">
  <title>AMCO Interior Design | Furniture in Ethiopia, Addis Ababa</title>
  <meta name="keywords" content="AMCO Interior Design, Furniture in Ethiopia, Furniture Store in Addis Ababa, Furniture in Addis Ababa with Price, Furniture in Addis, Furniture House in Addis Ababa, Furniture Shops in Addis Ababa, Furniture Design Ethiopia, Interior Design Addis Ababa">
    <title>{% if product %}Edit Product{% else %}Add Product{% endif %}</title>
    <style>
        body {
            font-family: 'Poppins', sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }

        .navbar-default {
            background-color: #2C3E50;
            border-color: #2C3E50;
            margin-bottom: 0;
            border-radius: 0;
        }

        .navbar-default .navbar-brand {
            color: white;
        }

        .navbar-default .navbar-nav>li>a {
            color: white;
        }

        .navbar-default .navbar-nav>li>a:hover,
        .navbar-default .navbar-nav>li>a:focus {
            background-color: #34495E;
            color: white;
        }

        h1 {
            text-align: center;
            margin-top: 50px;
            color: #2C3E50;
        }

        form {
            max-width: 400px;
            margin: auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
            color: #2C3E50;
        }

        input[type="text"],
        input[type="email"],
        input[type="file"],
        select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button[type="submit"] {
            display: block;
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 4px;
            background-color: #2C3E50;
            color: white;
            font-weight: bold;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #34495E;
        }

        .centered-text {
            text-align: center;
            margin-top: 50px;
            color: #2C3E50;
        }
    </style>
</head>

<body>
    <h1>{% if product %}Edit Product{% else %}Add New Product{% endif %}</h1>
    <form
        action="{% if product %}{{ url_for('product.edit_product', product_id=product.id) }}{% else %}{{ url_for('product.add_product') }}{% endif %}"
        method="post" enctype="multipart/form-data">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" {% if product %}value="{{ product.name }}" {% endif %} required>
        <label for="price">Price:</label>
        <input type="number" id="price" name="price" {% if product %}value="{{ product.price }}" {% endif %} required>
        <label for="image">Image:</label>
        <input type="file" id="image" name="image" accept="image/*" {% if not product %}required{% endif %}>
        <label for="description">Description:</label>
        <textarea id="description" name="description"
            required>{% if product %}{{ product.description }}{% endif %}</textarea>
        <button type="submit">{% if product %}Update Product{% else %}Add Product{% endif %}</button>
    </form>
    <p style="text-align: center; margin-top: 20px;">
        <a href="{{ url_for('admin.admin') }}">Back to Admin Panel</a>
    </p>

</body>

</html>

app/templates/applied_jobs.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
  
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Discover AMCO Interior Design for top-quality furniture and exceptional interior design services in Addis Ababa, Ethiopia. Visit our store for the best furniture prices and designs. Find furniture in Ethiopia, a furniture store in Addis Ababa, and interior design services.">
  <title>AMCO Interior Design | Furniture in Ethiopia, Addis Ababa</title>
  <meta name="keywords" content="AMCO Interior Design, Furniture in Ethiopia, Furniture Store in Addis Ababa, Furniture in Addis Ababa with Price, Furniture in Addis, Furniture House in Addis Ababa, Furniture Shops in Addis Ababa, Furniture Design Ethiopia, Interior Design Addis Ababa">
    <link rel="icon" type="image/png" href="/static/images/logo.png">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

  <style>
        body {
            background: white;
            font-family: 'Poppins', sans-serif;
        }
        .navbar-default {
            background-color: #11474D;
            border-color: #11474D;
        }
        .navbar-default .navbar-brand {
            color: white;
        }
        .navbar-default .navbar-nav>li>a {
            color: white;
        }
        .navbar-default .navbar-nav>li>a:hover,
        .navbar-default .navbar-nav>li>a:focus {
            background-color: #0A2C2F;
            color: white;
        }
        .container {
            margin-top: 20px;
        }
        .table th {
            color: white;
            background-color: rgba(0, 0, 0, 0.3);
        }
        .table td {
            background-color: rgba(0, 0, 0, 0.1);
        }
        .btn {
            margin-top: 10px;
        }
        nav ul li{
          position: relative;
          right: 300px;
        }
        .navbar-right {
            margin-right: 20px;
        }
        .navbar-right a {
            color: white;
            margin-left: 10px;
        }
    </style>
</head>
<body>
    <body class="login-page">
       
        <!-- Header -->
        <header class="header" id="header">
          <nav>
            <div class="logo-container">
              <a href="/"><img src="/static/images/logo.png" alt="Your Logo" class="logo"></a>
            </div>
            <ul id="menuList">
              <li><a id="home" href="/">Home</a></li>
              <li class="dropdown">
                <a class="dropbtn" href="#" onclick="toggleDropdown()" onmouseover="showDropdown()">About
                  <span class="fas fa-angle-down"></span>
                </a>
                <div class="dropdown-content" id="dropdownMenu">
                  <a id="about" href="/about">WHO WE ARE</a>
                  <a href="/">Portfolio</a>
                </div>
              </li>
              <li><a href="/">Service</a></li>
              <li><a id="products" href="/prod">Products</a></li>
              <li><a href="/">Contact</a></li>
              <li><a id="vacancy" href="/vacancy">Vacancy</a></li>
        <li><a id="login" href="sagin"><i class="fas fa-user"></i></a></li>
      </ul>
      <div class="menu-icon">
        <i class="fa-solid fa-bars" onclick="toggleMenu()"></i>
      </div>
    </nav>
  </header>

    <div class="container">
        <h1>Applied Jobs - Job ID: {{ job_id }}</h1>

        {% if applied_jobs %}
            <table class="table">
                <thead>
                    <tr>
                        <th>First Name</th> <!-- Change from Name to First Name -->
                        <th>Father Name</th> <!-- New column for Father Name -->
                        <th>Email</th>
                        <th>Gender</th>
                        <th>Age</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for applied_job in applied_jobs %}
                        <tr>
                            <td>{{ applied_job.first_name }}</td> <!-- Change to first_name -->
                            <td>{{ applied_job.father_name }}</td> <!-- New column for father_name -->
                            <td>{{ applied_job.applicant_email }}</td>
                            <td>{{ applied_job.gender }}</td>
                            <td>{{ applied_job.age }}</td>
                            <td>
                                {% if applied_job.cv_path %}
                                    <a href="{{ url_for('vacancy.download_cv', cv_path=applied_job.cv_path) }}" class="btn btn-primary">Download CV</a>
                                {% else %}
                                    No CV available
                                {% endif %}
                                <form method="post" action="{{ url_for('vacancy.delete_applied_job', applied_job_id=applied_job.id) }}" style="display: inline;">
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No jobs have been applied for.</p>
        {% endif %}
    </div>
</body>
<script>
    function toggleDropdown() {
      var dropdown = document.getElementById("dropdownMenu");
      if (dropdown.style.display === "block") {
        dropdown.style.display = "none";
      } else {
        dropdown.style.display = "block";
      }
    }
  
    function showDropdown() {
      var dropdown = document.getElementById("dropdownMenu");
      dropdown.style.display = "block";
    }
  
    // Hide dropdown when clicking outside
    window.onclick = function(event) {
      if (!event.target.matches('.dropbtn')) {
        var dropdowns = document.getElementsByClassName("dropdown-content");
        for (var i = 0; i < dropdowns.length; i++) {
          var openDropdown = dropdowns[i];
          if (openDropdown.style.display === "block") {
            openDropdown.style.display = "none";
          }
        }
      }
    }
  </script>
</html>

app/templates/create_blog_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Discover AMCO Interior Design for top-quality furniture and exceptional interior design services in Addis Ababa, Ethiopia. Visit our store for the best furniture prices and designs. Find furniture in Ethiopia, a furniture store in Addis Ababa, and interior design services.">
    <title>AMCO Interior Design | Furniture in Ethiopia, Addis Ababa</title>
    <meta name="keywords" content="AMCO Interior Design, Furniture in Ethiopia, Furniture Store in Addis Ababa, Furniture in Addis Ababa with Price, Furniture in Addis, Furniture House in Addis Ababa, Furniture Shops in Addis Ababa, Furniture Design Ethiopia, Interior Design Addis Ababa">  
</head>
<body>
    <h1>Create Blog Post</h1>
    <form action="/badmin/blog/create" method="POST">
        <label for="title">Title:</label><br>
        <input type="text" id="title" name="title" required><br>
        <label for="content">Content:</label><br>
        <textarea id="content" name="content" required></textarea><br>
        <label for="author">Author:</label><br>
        <input type="text" id="author" name="author" required><br><br>
        <button type="submit">Create</button>
    </form>
    
    
</body>
</html>

app/templates/edit_blog_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Discover AMCO Interior Design for top-quality furniture and exceptional interior design services in Addis Ababa, Ethiopia. Visit our store for the best furniture prices and designs. Find furniture in Ethiopia, a furniture store in Addis Ababa, and interior design services.">
    <title>AMCO Interior Design | Furniture in Ethiopia, Addis Ababa</title>
    <meta name="keywords" content="AMCO Interior Design, Furniture in Ethiopia, Furniture Store in Addis Ababa, Furniture in Addis Ababa with Price, Furniture in Addis, Furniture House in Addis Ababa, Furniture Shops in Addis Ababa, Furniture Design Ethiopia, Interior Design Addis Ababa">  
</head>
<body>
    <h1>Edit Blog Post</h1>
    <form action="{{ url_for('blog.edit_blog_post', id=post.id) }}" method="POST">
        <label for="title">Title:</label><br>
        <input type="text" id="title" name="title" value="{{ post.title }}"><br>
        <label for="content">Content:</label><br>
        <textarea id="content" name="content">{{ post.content }}</textarea><br>
        <label for="author">Author:</label><br>
        <input type="text" id="author" name="author" value="{{ post.author }}"><br><br>
        <button type="submit">Update</button>
    </form>
</body>
</html>

app/templates/edit_event.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Discover AMCO Interior Design for top-quality furniture and exceptional interior design services in Addis Ababa, Ethiopia. Visit our store for the best furniture prices and designs. Find furniture in Ethiopia, a furniture store in Addis Ababa, and interior design services.">
    <title>AMCO Interior Design | Furniture in Ethiopia, Addis Ababa</title>
    <meta name="keywords" content="AMCO Interior Design, Furniture in Ethiopia, Furniture Store in Addis Ababa, Furniture in Addis Ababa with Price, Furniture in Addis, Furniture House in Addis Ababa, Furniture Shops in Addis Ababa, Furniture Design Ethiopia, Interior Design Addis Ababa">  
</head>
<body>
    <h1>Edit Event</h1>
    <form action="{{ url_for('blog.edit_event', id=event.id) }}" method="POST">
        <label for="title">Title:</label><br>
        <input type="text" id="title" name="title" value="{{ event.title }}"><br>
        <label for="description">Description:</label><br>
        <textarea id="description" name="description">{{ event.description }}</textarea><br>
        <label for="date">Date:</label><br>
        <input type="date" id="date" name="date" value="{{ event.date }}"><br>
        <label for="location">Location:</label><br>
        <input type="text" id="location" name="location" value="{{ event.location }}"><br><br>
        <button type="submit">Update</button>
    </form>
</body>
</html>